### ISSUE TITLE
Typescript usage within readme.md is incorrect

### ISSUE THREAD

**Issue by DeadEnglish** [NativeScript/nativescript-brightness#14]
The typescript usage is incorrect/incomplete. Currently it just tells the user to `import * as brightness from 'nativescript-brightness';` which is incorrect. Using the way above you would have to instantiate the class as follows:

```typescript
import * as brightness from 'nativescript-brightness';

const screenBrightness = new brightness.Brightness();
```

Ideally this should be written as below:

```typescript
import { Brightness } from `nativescript-brightness';

const screenBrightness = new Brightness();
```

The readme is also missing the instantiation of the class. This is important as without it you're unable to use the example within the `README.md.`

**Comment by elena-p** [comment]
Hi @DeadEnglish,
Thank you for your comments. There is a [PR](https://github.com/NativeScript/nativescript-brightness/pull/17/files) on its way.
