### ISSUE TITLE
Incompatibility of plugin with older versions of android SDK (< 23)

### ISSUE THREAD

**Issue by fernandomeneghetti** [NativeScript/nativescript-brightness#18]
### Make sure to check the demo app(s) for sample usage 
Checked. The problem also occurs.

### Make sure to check the existing issues in this repository 
Checked.

### Which platform(s) does your issue occur on?
- Android 
- Sdk version < 23. Android 4.4.2, 5.0.1
- emulator & device. (Galaxy S3, Galaxy S4)

### Please, provide the following version numbers that your issue occurs with:
- CLI: 5.2.2
- Cross-platform modules: 5.2.1
- Runtime(s): 5.2.0
- Plugin(s): 
    "@angular/cli": "~7.2.0",
    "@angular/compiler-cli": "~7.2.0",
    "@nativescript/schematics": "^0.5.1",
    "@ngtools/webpack": "~7.2.0",
    "babel-traverse": "^6.26.0",
    "babel-types": "^6.26.0",
    "babylon": "6.4.5",
    "codelyzer": "^4.5.0",
    "cross-var": "^1.1.0",
    "lazy": "1.0.11",
    "nativescript-dev-sass": "^1.6.0",
    "nativescript-dev-typescript": "^0.8.0",
    "nativescript-dev-webpack": "^0.20.2",
    "shx": "^0.3.2",
    "ts-loader": "^4.3.1",
    "tslint": "^5.11.0",
    "typescript": "~3.1.1"

### Please, tell us how to recreate the issue in as much detail as possible. 
Just run on some device with SDK <23

### Is there any code involved? carteira.component.ts
...
import { Brightness } from "nativescript-brightness";
...

ngOnInit(): void {
...
this.setBrightness(50);
...
}

    setBrightness(intensity: number): void {
        if (isAndroid && android.os.Build.VERSION.SDK_INT < 23) {
            const attr = topmost().android.activity.getWindow().getAttributes();
            attr.screenBrightness = intensity / 100;
            topmost().android.activity.getWindow().setAttributes(attr);
        } else {
            const brightness = new Brightness();
            brightness.set({ intensity });
        }
    }

    getBrightness(): number {
        const brightness = new Brightness();
        return brightness.get();
    }

**Comment by elena-p** [comment]
Hi @fernandomeneghetti,

You are right, nativescript-brightness plugin currently supports only android >= 23 sdk versions. 
I opened a [PR](https://github.com/NativeScript/nativescript-brightness/pull/19) with your suggestion.

**Comment by DimitarTodorov** [comment]
Issue is fixed with latest version of nativescript-brightness - 1.0.1
